name: Telegram Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  telegram_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Check api
        run: node fetchGroup.js ${{ secrets.TELEGRAM_TOKEN }}