name: Telegram Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  telegram_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Check api
        run: node fetchGroup.js ${{ secrets.TELEGRAM_TOKEN }}