name: Telegram Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  telegram_worker:
    name: Telegram Worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Setup git and fetch
        continue-on-error: true
        run: |
          git config --global --add safe.directory /github/workspace
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git config pull.rebase true
          git fetch origin deployThemes

      - name: Pull branch
        continue-on-error: true
        run: |
          git checkout -b deployThemes
          git pull origin deployThemes

      - name: Fetch Theme packs
        run: node fetchGroup.js ${{ secrets.TELEGRAM_TOKEN }}

      - name: Create commit
        continue-on-error: true
        run: |
          git add deploy
          git commit -m "Add new Themes"
          git push -u origin deployThemes

      - name: Create Pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'deployThemes'
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: 'deployThemes'
          pr_body: 'Add new Themes'
          pr_title: 'Automatic Deploy script'
