name: Telegram Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  telegram_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Fetch Theme packs
        run: node fetchGroup.js ${{ secrets.TELEGRAM_TOKEN }}

      - name: Create commit
        continue-on-error: true
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git checkout -b deployThemes
          git add deploy
          git commit -m "Add new Themes"
          git push -u origin deployThemes

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: 'Add new Themes'
          pr_title: 'Automatic Deploy script'